---
- hosts: webservers
  vars:
    http_port: 80
    max_clients: 200
    remote_user: root
  tasks: 
  - name: ensure libselinux-python is installed before apache is installed
    shell: if rpm -q libselinux-python > /dev/null; then echo "installed"; else echo "not_installed"; fi
    #ignore_errors: true
    register: rpm_check
  - debug: msg="{{ rpm_check.stdout }}"
  - name: execute script if libselinux-python is not installed
    yum:
      name: libselinux-python
      state: latest
    when: rpm_check.stdout == "not_installed"
  - name: ensure apache is at the latest version
    yum:
      name: httpd
      state: latest
  - name: replace default index.html
    template:
      src: /static_files/index.html
      dest: /var/www/html/
    notify:
    - restart apache
  - name: ensure apache is running
    service:
      name: httpd
      state: started
      enabled: yes
  handlers:
    - name: restart apache
      service:
        name: httpd
        state: restarted
